# Numpy Array Operation

In [1]:
import numpy as np; # import numpy library and set alias

### Inexing and Slicing

In [2]:
# For 1D array
np_1Darr=np.arange(0,40,2) # create an 1D array using arange method
print(f"Array is: {np_1Darr}") # print the np_arr
print(f"Basic Slicing: {np_1Darr[2:8]}") # here use slicing where [starting Index:Ending Index]
print(f"Basic Slicing with Steps: {np_1Darr[2:12:2]}") # here also use slicing with steps where [Starting index:EndingIndex: Steps(skip how many value)]
print(f"Specific Element:{np_1Darr[4]}")
print(f"Negtive Indexing: {np_1Darr[-5]}")# Return the value which are lies on index 5 from right side


Array is: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
Basic Slicing: [ 4  6  8 10 12 14]
Basic Slicing with Steps: [ 4  8 12 16 20]
Specific Element:8
Negtive Indexing: 30


In [3]:
#For 2D array
np_2D_arr=np.array([[1,2,3],[4,5,6],[7,8,9]]) # Create a matrix 
print(f"Marix is: {np_2D_arr}") # print matrix
print(f"Specific Element:{np_2D_arr[2,0]}") # Get a specific element from matrix where [row,column]
print(f"Entire Row: {np_2D_arr[1]}") # Get an entire row 
print(f"Entire Column: {np_2D_arr[:,1]}")# Get an entire column


Marix is: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element:7
Entire Row: [4 5 6]
Entire Column: [2 5 8]


### Sorting

In [ ]:
# For 1D Array or Vector
unsortedArray=np.array([2,5,-1,0,53,2,7,3,9,34,6,9]) # Vector or 1-D Array
print(f"Unsorted Array:{unsortedArray}") # print Un_Sorted Array
print(f"Sorted Array:{np.sort(unsortedArray)}") # Print the sorted array using sort build function 



In [ ]:
# For 2D Array or Matrix
unsorted_2D_arr=np.array([[1,4],[3,2],[5,3]]) # Matrix or 2D array
print("Unsorted 2D Array: ",unsorted_2D_arr) # print Unsorted array
print(f"Sorted 2D Array in Column wise: {np.sort(unsorted_2D_arr,axis=0)}") # sort column wise because axis=0 is represent column sort
print(f"Sorted 2D Array in Row wise: {np.sort(unsorted_2D_arr,axis=1)}") # sort row wise becasue axis-1 is represent row sort


### Filter

In [4]:
np_arr_filter=np.arange(1,11)
print(f"Array is: {np_arr_filter}")
oddNum=np_arr_filter[np_arr_filter%2==1]
print("Filter the Odd number by expression is: ",oddNum)

# Filter with mask


mask=np_arr_filter>8 # mask have the whole formula or expression which help to filter
print(f"Filter Array by mask is:{np_arr_filter[mask]} ")


# Fancy Indexing 
indices=[3,6,9]
print("Filter by indices:",np_arr_filter[indices])

#np.where()
where_result=np.where(np_arr_filter<5)
print("Where result: ",where_result)
print("Filter by where is:",np_arr_filter[where_result])


# conditional with where
condition_array=np.where(np_arr_filter>5,np_arr_filter*3,np_arr_filter)# here we apply tarnary operator of short if-else statement
print("Condition Array is: ",condition_array)


Array is: [ 1  2  3  4  5  6  7  8  9 10]
Filter the Odd number by expression is:  [1 3 5 7 9]
Filter Array by mask is:[ 9 10] 
Filter by indices: [ 4  7 10]
Where result:  (array([0, 1, 2, 3]),)
Filter by where is: [1 2 3 4]
Condition Array is:  [ 1  2  3  4  5 18 21 24 27 30]


## Adding and Removing Data

In [5]:
arr1=np.array([1,2,3])
arr2=np.arange(4,7)
arr3=np.array([7,8,9])
print(f"Array_1: {arr1} and Array_2: {arr2}")

# merege both arr 1 and 2
mergeArray=np.concat([arr1,arr2]) # concat or concatination both are same both are work for merge like spread operator in javascript
mergeArray1=np.concatenate([arr1,arr2,arr3])
print(f"Merge Array is: {mergeArray}")
print(f"Merge Array-1 is: {mergeArray1}")

print("Array Compatibility shapes:",arr1.shape==arr2.shape==arr3.shape) # here we check the lenght are same or not for any operation using shap method like if add 3 matrix then there must be same number of rows and column 

Array_1: [1 2 3] and Array_2: [4 5 6]
Merge Array is: [1 2 3 4 5 6]
Merge Array-1 is: [1 2 3 4 5 6 7 8 9]
Array Compatibility shapes: True


#### Add new rows and column in a matrix

In [6]:
# add new rows with the help of vstack
towDArray=np.array([[1,2],[3,4]])
print("2D array: ",towDArray)

new_row=np.array([7,8])
new_row1=np.array([12.34])

with_new_Row=np.vstack((new_row,towDArray)) # vstack add new rows in exiting matrix if add new row at begining then comes begining and at last then we see new array at last  like
with_new_Row1=np.vstack((towDArray,new_row)) 

print(f"New Array with new row:{with_new_Row}")
print(f"New Array with new row:{with_new_Row1}")

2D array:  [[1 2]
 [3 4]]
New Array with new row:[[7 8]
 [1 2]
 [3 4]]
New Array with new row:[[1 2]
 [3 4]
 [7 8]]


In [7]:
# add new column with the help of hstack

towDArray1=np.array([[12,1],[45,5]])
new_col=np.array([[80,90],[900,890]])

with_new_Row1=np.vstack((new_col,towDArray1))
with_new_col=np.hstack((towDArray1,new_col))
print(f"With new col:{with_new_col}")
# print(f"With new row:{with_new_Row1}")

With new col:[[ 12   1  80  90]
 [ 45   5 900 890]]


### Removing Operation or Deleting Operaion in numpy

In [ ]:
arr4=np.arange(1,10)
print("Array: ",arr4)

deleteElement=np.delete(arr4,3) # delete return whole array again remove the particular element which we delete

print("Deleted Element: ",deleteElement)
print("Array: ",arr4)

Array:  [1 2 3 4 5 6 7 8 9]
Deleted Element:  [1 2 3 5 6 7 8 9]
Array:  [1 2 3 4 5 6 7 8 9]
