In [1]:
import numpy as np;

In [2]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.random.rand(3,3)
arr3=np.zeros((4,4))

## Save in local Disk not in RAM

In [3]:
np.save("arr1.npy",arr1)
np.save("arr2.npy",arr2)
np.save("arr3.npy",arr3)

### Loading Save Array

In [4]:
load_arr1=np.load('arr1.npy')
load_arr2=np.load('arr2.npy')
load_arr3=np.load('arr3.npy')
print("Loaded Array-1 is: ",load_arr1)
print("Loaded Array-2 is: ",load_arr2.round(2))
print("Loaded Array-3 is: ",load_arr3)

Loaded Array-1 is:  [[1 2 3]
 [4 5 6]]
Loaded Array-2 is:  [[0.41 0.17 0.63]
 [0.26 0.51 0.88]
 [0.4  0.5  0.43]]
Loaded Array-3 is:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
