# Numpy

In [ ]:
import numpy as np # import numpy lib
import time

# List vs Array

In [ ]:
py_list=[1,2,3,4]
print(f"Python List: {py_list}")
print(f"Python List multiplication : {py_list*2}") # it duplicate the value of the original list one more types orignal + new so two times

In [ ]:
np_array=np.array([1,2,3,4])
print(f"Numpy array:{np_array}")
print(f"Numpy array:{np_array*2}") # here we multiply , the scalar value multiply on each element inside the array(1D array or single row of matrix)

In [ ]:
start=time.time()
py_list1=[i*2 for i in range(100000)]
print(f"\nList Operation Time:{time.time()-start}")
start=time.time()
np_array1=np.arange(10,100000,3)*2 # arrange(start , stop, step)
print(np_array1)
print(f"\nNumpy Operation Time:{time.time()-start}")

# Creating Array from Scratch with numpy method

In [ ]:
np_zeros=np.zeros((2,3)) # it create 2 by 3 matrix and this conatain 0 as it's elements
print(f"Matrix:\n{np_zeros}")
np_ones=np.ones((2,3)) # it create 2 by 3 matrix and this conatain 1 as it's elements
print(f"Matrix:\n{np_ones}")
np_full=np.full((2,3),9) # it create 2 by 3 matrix and this conatain 9 as it's elements
print(f"Matrix:\n{np_full}")

np_random=np.random.random((4,4))
fix=np_random.round(0)*10

print(f"Matrix:\n{np_random}")
print(f"fix:{fix}")

Matrix:
[[0. 0. 0.]
 [0. 0. 0.]]
Matrix:
[[1. 1. 1.]
 [1. 1. 1.]]
Matrix:
[[9 9 9]
 [9 9 9]]
Matrix:
[[0.34002851 0.93318507 0.16173025 0.4001632 ]
 [0.2828426  0.31872734 0.08958348 0.16085947]
 [0.08840661 0.52599637 0.08772778 0.15161133]
 [0.27339268 0.98289197 0.78169325 0.29991495]]
fix:<class 'int'>
