# Numpy

In [43]:
import numpy as np # import numpy lib
import time

# List vs Array

In [44]:
py_list=[1,2,3,4]
print(f"Python List: {py_list}")
print(f"Python List multiplication : {py_list*2}") # it duplicate the value of the original list one more types orignal + new so two times

Python List: [1, 2, 3, 4]
Python List multiplication : [1, 2, 3, 4, 1, 2, 3, 4]


In [45]:
np_array=np.array([1,2,3,4])
print(f"Numpy array:{np_array}")
print(f"Numpy array:{np_array*2}") # here we multiply , the scalar value multiply on each element inside the array(1D array or single row of matrix)

Numpy array:[1 2 3 4]
Numpy array:[2 4 6 8]


In [46]:
start=time.time()
py_list1=[i*2 for i in range(100000)]
print(f"\nList Operation Time:{time.time()-start}")
start=time.time()
np_array1=np.arange(10,100000,3)*2 # arrange(start , stop, step)
print(np_array1)
print(f"\nNumpy Operation Time:{time.time()-start}")


List Operation Time:0.037786006927490234
[    20     26     32 ... 199982 199988 199994]

Numpy Operation Time:0.0032858848571777344


# Creating Array from Scratch with numpy method

In [ ]:
np_zeros=np.zeros((2,3)) # it create 2 by 3 matrix and this conatain 0 as it's elements
print(f"Matrix:\n{np_zeros}")
np_ones=np.ones((2,3)) # it create 2 by 3 matrix and this conatain 1 as it's elements
print(f"Matrix:\n{np_ones}")
np_full=np.full((2,3),9) # it create 2 by 3 matrix and this conatain 9 as it's elements
print(f"Matrix:\n{np_full}")

np_random=np.random.random((4,4))
fix=np_random.round(0)*10

print(f"Matrix:\n{np_random}")
print(f"fix:{fix}")
np_sequence=np.arange(0,20,3)
print(f"Sequence: {np_sequence}")




Matrix:
[[0. 0. 0.]
 [0. 0. 0.]]
Matrix:
[[1. 1. 1.]
 [1. 1. 1.]]
Matrix:
[[9 9 9]
 [9 9 9]]
Matrix:
[[0.99204224 0.21627085 0.01818023 0.64141579]
 [0.78473033 0.36643209 0.48609381 0.4582173 ]
 [0.47674959 0.59582712 0.43162558 0.55703228]
 [0.93417546 0.1572279  0.38027862 0.75248475]]
fix:[[10.  0.  0. 10.]
 [10.  0.  0.  0.]
 [ 0. 10.  0. 10.]
 [10.  0.  0. 10.]]
Sequence: [ 0  3  6  9 12 15 18]


### Vector  Matrix and Tensor

In [49]:
vector=np.array([1,2,3,4,5]) # 1D array is called vector
print(f"Vector is: {vector}")


matrix=np.array([[1,2,3]]) # 2D array is called matrix
print(f"Matrix is: {matrix}")


tensor=np.array([[[2,3],[12,45],[4,5]]]) # More than 2D array is called Tensor
print(f"Tensor:{tensor}")



Vector is: [1 2 3 4 5]
Matrix is: [[1 2 3]]
Tensor:[[[ 2  3]
  [12 45]
  [ 4  5]]]


#### Array Properties

In [ ]:
np_arr=np.array([
    [1,2],
    [3,4]
])

print(f"Shap of np_arr:{np_arr.shape}") # this property of array return the total number of row and column in a matrix 
print(f"Dimension of np_arr:{np_arr.ndim}") # this property of array return the dimension of matrix
print(f"Size of np_arr:{np_arr.size}") # this property of array return the size of total number of element in the matrix
print(f"DataType of np_arr:{np_arr.dtype}") # this property of array return the datatype of the array

## Array Reshapping