# Advance Operation with Business Example

In [1]:
import numpy as np;
# import matplotlib.pyplot as plt;

In [2]:
salesData=np.array([
    [1,15000,18000,220000,250000],
    [2,17000,10000,960000,190000],
    [3,13000,18000,300000,110000],
    [4,14000,19000,200000,150000],
    [5,15000,14000,800000,180000]
])
print("Data Analysis")
print("Sales Data is: ",salesData)
print("Sales Data shap is: ",salesData.shape)
print("First Three resturant Sale:",salesData[0:3])


Data Analysis
Sales Data is:  [[     1  15000  18000 220000 250000]
 [     2  17000  10000 960000 190000]
 [     3  13000  18000 300000 110000]
 [     4  14000  19000 200000 150000]
 [     5  15000  14000 800000 180000]]
Sales Data shap is:  (5, 5)
First Three resturant Sale: [[     1  15000  18000 220000 250000]
 [     2  17000  10000 960000 190000]
 [     3  13000  18000 300000 110000]]


## Tatal Sales per Year

In [3]:
total_yearly=np.sum(salesData[:,1:],axis=0)
print("Total Yearly: ",total_yearly)

total_resturantly=np.sum(salesData[:,1:],axis=1)
print("Total Resturant wise: ",total_resturantly)


minYearly=np.min(salesData[:,1:],axis=0)
print(f"Min Yearly:{minYearly}")

minResturantly=np.min(salesData[:,1:],axis=1)
print(f"Min Resturantly:{minResturantly}")


maxYearly=np.max(salesData[:,1:2])
print("Max Sales of Specific Yealy: ",maxYearly)

maxResturantly=np.max(salesData[2:3,],axis=1)
print("Max Sales of Specific Resturantly: ",maxResturantly)



avgRestrantly=np.average(salesData[:,1:],axis=1)
print(f"Average Resturantly:{avgRestrantly}")

avgYearly=np.mean(salesData[:,1:],axis=0)
print(f"Average Yearly:{avgYearly}")



accumlatarSaleResturantly=np.cumsum(salesData[:,1:],axis=1)
print("Accumulate Sum of Resturant:",accumlatarSaleResturantly)


accumlatorSaleYearly=np.cumsum(salesData[:,1:],axis=0)
print("Accumulate Sum of Yearly:",accumlatorSaleYearly)



Total Yearly:  [  74000   79000 2480000  880000]
Total Resturant wise:  [ 503000 1177000  441000  383000 1009000]
Min Yearly:[ 13000  10000 200000 110000]
Min Resturantly:[15000 10000 13000 14000 14000]
Max Sales of Specific Yealy:  17000
Max Sales of Specific Resturantly:  [300000]
Average Resturantly:[125750. 294250. 110250.  95750. 252250.]
Average Yearly:[ 14800.  15800. 496000. 176000.]
Accumulate Sum of Resturant: [[  15000   33000  253000  503000]
 [  17000   27000  987000 1177000]
 [  13000   31000  331000  441000]
 [  14000   33000  233000  383000]
 [  15000   29000  829000 1009000]]
Accumulate Sum of Yearly: [[  15000   18000  220000  250000]
 [  32000   28000 1180000  440000]
 [  45000   46000 1480000  550000]
 [  59000   65000 1680000  700000]
 [  74000   79000 2480000  880000]]


## Graphical Representation

In [ ]:
plt.figure(figsize=(10,6))
plt.plot(np.mean(accumlatorSaleYearly,axis=0))
plt.title("Average of cumulative Sales of accors Yearly")
plt.ylabel("Resturant Sales")
plt.xlabel("Yearly Sales")
plt.grid(True)
plt.show()

# Vector Operation

In [ ]:
vector1=np.array([1,2,3,4,5])
vector2=np.array([6,7,8,9,10])

# Vector addition

print()
