# Advance Operation with Business Example

In [3]:
import numpy as np;


In [4]:
salesData=np.array([
    [1,15000,18000,220000,250000],
    [2,17000,10000,960000,190000],
    [3,13000,18000,300000,110000],
    [4,14000,19000,200000,150000],
    [5,15000,14000,800000,180000],
])

print("Sales Data is: ",salesData)

Sales Data is:  [[     1  15000  18000 220000 250000]
 [     2  17000  10000 960000 190000]
 [     3  13000  18000 300000 110000]
 [     4  14000  19000 200000 150000]
 [     5  15000  14000 800000 180000]]
