# Advance Operation with Business Example

In [6]:
import numpy as np;

In [ ]:
salesData=np.array([
    [1,15000,18000,220000,250000],
    [2,17000,10000,960000,190000],
    [3,13000,18000,300000,110000],
    [4,14000,19000,200000,150000],
    [5,15000,14000,800000,180000]
])
print("Data Analysis")
print("Sales Data is: ",salesData)
print("Sales Data shap is: ",salesData.shape)


Data Analysis
Sales Data is:  [[     1  15000  18000 220000 250000]
 [     2  17000  10000 960000 190000]
 [     3  13000  18000 300000 110000]
 [     4  14000  19000 200000 150000]
 [     5  15000  14000 800000 180000]]


(5, 5)