# Basic Properties and Method of the numpy Array

In [11]:
import numpy as np;

arr=np.array([1,2,3])
print("Data type of arr:",arr.dtype)
changType=arr.astype(float) # does not change the original dtype
print("Change the data type of the above array is: ",changType)
print("Data type of arr:",changType.dtype)
print("Data type of arr:",arr.dtype)
print("dimension of arr:",arr.ndim)
print("Size of Array: ",arr.size)
print("Shpa of Array is: ",arr.shape)
print("Mean of Array is: ",np.mean(arr))
print("Standard Deviation of Array is: ",np.std(arr))
print("Variance of Array is: ",np.var(arr))



Data type of arr: int64
Change the data type of the above array is:  [1. 2. 3.]
Data type of arr: float64
Data type of arr: int64
dimension of arr: 1
Size of Array:  3
Shpa of Array is:  (3,)
Mean of Array is:  2.0
Standard Deviation of Array is:  0.816496580927726
Variance of Array is:  0.6666666666666666


# Manipulation in array

In [25]:
# how to insert new element in vector or 1D arry
arr_1D=np.array([1,2,3,4,5])
print("Array is: ",arr_1D)
insertNewEle=np.insert(arr_1D,2,50) # .insert(array,index, newEle) 
print("Array with newly inserted array:",insertNewEle)

# How to insert new row or column in matrix or 2D array
arr_2D=np.arange(1,10).reshape(3,3)
print(f"2D Array is:{arr_2D}")
insertNewEleIn2D=np.insert(arr_2D,1,50,axis=0) # .insert(array,index,newEle,axix=1/0)
print("Array with newly added or inserted Ele",insertNewEleIn2D)
insertEleIn2D=np.insert(arr_2D,1,50,axis=1)
print("Array with newly added or inserted Ele",insertEleIn2D)
insertEleInMatrix=np.insert(arr_2D,1,[11,22,33],axis=1)
print("Array with newly added or inserted Ele",insertEleInMatrix)
insertEleInMatrixCol=np.insert(arr_2D,1,[110,90,33],axis=0)
print("Array with newly added or inserted Ele",insertEleInMatrixCol)

Array is:  [1 2 3 4 5]
Array with newly inserted array: [ 1  2 50  3  4  5]
2D Array is:[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array with newly added or inserted Ele [[ 1  2  3]
 [50 50 50]
 [ 4  5  6]
 [ 7  8  9]]
Array with newly added or inserted Ele [[ 1 50  2  3]
 [ 4 50  5  6]
 [ 7 50  8  9]]
Array with newly added or inserted Ele [[ 1 11  2  3]
 [ 4 22  5  6]
 [ 7 33  8  9]]
Array with newly added or inserted Ele [[  1   2   3]
 [110  90  33]
 [  4   5   6]
 [  7   8   9]]
